In [1]:
import subspaceImage as si
import pandas as pd

In [2]:
df = pd.read_csv('/home/ayushi/Desktop/subspace-search/auto-mpg-7d-order.csv')
df['label']=1
df=df[['mpg','cylinders','displacement','label']]

In [3]:
df.head()

mpg  cylinders  displacement  label
0   9.0          8         304.0      1
1  10.0          8         360.0      1
2  10.0          8         307.0      1
3  11.0          8         318.0      1
4  11.0          8         429.0      1

In [4]:
obj = si.subspaceImage()
obj.setDataset(df.iloc[:,:-1],df.iloc[:,-1])
obj.setAllSubspaces()

3


In [5]:
obj.printAllsubspaces()
obj.giveColorToEachSubspace()
obj.printColorToEachSubspace()
obj.createLegend()
allImages,hm = obj.getHeidiImagesForAllSubspaces()

(0,)
(1,)
(2,)
(0, 1)
(0, 2)
(1, 2)
(0, 1, 2)
(0,) : [51, 98, 107]
(1,) : [240, 74, 28]
(2,) : [219, 65, 226]
(0, 1) : [72, 198, 33]
(0, 2) : [96, 56, 90]
(1, 2) : [62, 86, 23]
(0, 1, 2) : [112, 146, 236]
['mpg', 'cylinders', 'displacement']
(0,)
(1,)
(2,)
(0, 1)
(0, 2)
(1, 2)
(0, 1, 2)


In [6]:
hm

[array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]], dtype=uint64),
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]], dtype=uint64),
 array([[1, 0, 1, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]], dtype=uint64),
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]], dtype=uint64),
 array([[1, 0, 1, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 1, ..., 0, 

In [15]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [18]:
mse_matrix = np.zeros((len(hm),len(hm)))

In [20]:
for i in range(len(hm)):
    for j in range(len(hm)):
        mse_matrix[i][j]=1-mean_squared_error(hm[i],hm[j])

In [21]:
mse_matrix

array([[1.        , 0.8139317 , 0.8255935 , 0.96675864, 0.83738546,
        0.8255935 , 0.83738546],
       [0.8139317 , 1.        , 0.83122918, 0.82762391, 0.83001874,
        0.83122918, 0.83004477],
       [0.8255935 , 0.83122918, 1.        , 0.83925968, 0.97661131,
        0.99979175, 0.97661131],
       [0.96675864, 0.82762391, 0.83925968, 1.        , 0.85192368,
        0.83929873, 0.85193669],
       [0.83738546, 0.83001874, 0.97661131, 0.85192368, 1.        ,
        0.97666337, 0.99996095],
       [0.8255935 , 0.83122918, 0.99979175, 0.83929873, 0.97666337,
        1.        , 0.97666337],
       [0.83738546, 0.83004477, 0.97661131, 0.85193669, 0.99996095,
        0.97666337, 1.        ]])